#pragma once

#define Q_QMETAUI_FORMS_LOG true
#define Q_QMETAUI_FORMS_LOG_VERBOSE false
#define Q_QMETAUI_FORMS_LOG_SUPER_VERBOSE false

#if Q_QMETAUI_FORMS_LOG_VERBOSE
#undef Q_QMETAUI_FORMS_LOG
#define Q_QMETAUI_FORMS_LOG true
#endif

#if Q_QMETAUI_FORMS_LOG_SUPER_VERBOSE
#undef Q_QMETAUI_FORMS_LOG
#undef Q_QMETAUI_FORMS_LOG_VERBOSE

#define Q_QMETAUI_FORMS_LOG true
#define Q_QMETAUI_FORMS_LOG_VERBOSE true
#endif
